apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi  # Adjust the storage size as needed
