{{if index .Values.global "externalSecret" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-eso-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mongodb-eso-secret-store
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.awsSecretName }}
{{- end }}